### ISSUE TITLE
Facbook.js in mobile issue

### ISSUE THREAD

**Issue by omer72** [thaiat/ionic-facebook#1]
Hi, 
I loved your presentation in the last meeting and i want to use the Facebook.js module, but I there is an with running it on mobile, it seems to me that you copy pase the 2 lines: 
if(!runningInCordova) {
                window.location = FB_LOGIN_URL + '?client_id=' + fbAppId + '&redirect_uri=' + oauthRedirectURL + '&response_type=token&display=popup&scope=' + fbScope;
            } else {
                window.location = FB_LOGIN_URL + '?client_id=' + fbAppId + '&redirect_uri=' + oauthRedirectURL + '&response_type=token&display=popup&scope=' + fbScope;
            }

what should be the correct code for running in cordova env?

**Comment by thaiat** [comment]
Hi @omer72 , thanks for you comment.

You are correct, the facebook service will not work as is when embedded with cordova. The scope of the demo was outside of cordova plugins

You have several choices: 
- adapt the service to do what is done here : https://github.com/thaiat/angular-fbopen/blob/master/angular-fbopen.js
  That is: open a new window, listen for loadstart event on it, and grab the token
- Use ngCordova like in this project : https://github.com/nraboy/ng-cordova-facebook-example

Let me know how it goes
