### ISSUE TITLE
How to add platforms

### ISSUE THREAD

**Issue by ghost** [thaiat/ionic-facebook#2]
Hello, thanks for sharing your project.

I can't figure out how to add a platform (ios or android) using ionic to your project, can you give me a clue ?

**Comment by thaiat** [comment]
hi @SInzunza ,
this project is built as a standard web page project. For you to install it with cordova, you would have to start over a new mobile project and copy around the files. Also make sure you adapt the facebook connection service as with cordova you need to do it differently...

hope this helps a bit

**Comment by ghost** [comment]
@thaiat First thank you very much for this beautiful repo. I am curious to know what do you think is the best way to release this web app to the app stores?

**Comment by thaiat** [comment]
@herve1976 your best shot is to use my generator (https://github.com/thaiat/generator-angular-famous-ionic) and scaffold a new mobile project with the following command:

```
yo angular-famous-ionic --mobile
```

then rescaffold the modules, services and controller from this repo into the new one.
then do 

```
gulp cordova:all
```

**Comment by ghost** [comment]
Merci @thaiat pour ton aide et toutes ces bonnes info mais ca a l'air bien trop compliqué pour moi pour l'instant. J'aurais bien voulu voir une version mobile de cette app. Je vais essayer de developper une version avec seulement Ionic. 

Keep up the good job. 

Hervé
