### ISSUE TITLE
Feed not working

### ISSUE THREAD

**Issue by ghost** [thaiat/ionic-facebook#3]
After successfully login, I get the following error on the console and nothing appears. Any idea why?

Failed to load resource: the server responded with a status of 403 (Forbidden)
https://graph.facebook.com/me/home?access_token=CAAJPbHrH62kBAO5Sf5In3JUTyZ…ll_picture,likes,description,comments,from,story,message,name,created_time 

Cordially,

Hervé

**Comment by thaiat** [comment]
it means your access token is not valid. It probably has to do with how you declared your application (restricted access) or the set of app_id, app_secret you are using...

**Comment by ghost** [comment]
Here is what the facebook link gives me:
error: {
message: "(#200) Requires extended permission: read_stream",
type: "OAuthException",
code: 200
}

But I dont see in FB where to do this permission. 
Where do I check if my app is restricted? 
Do I have to enter the app-secret on your code?

H

**Comment by thaiat** [comment]
you have to enter your app id here : https://github.com/thaiat/ionic-facebook/blob/master/client/scripts/main.js#L16

fb has a good tutorial (or just google it) to guide you through the steps

**Comment by herve1976** [comment]
it s the first thing I did. I could not login without doing this.
H

**Comment by herve1976** [comment]
Could you make sure the code is still working on your side please?

**Comment by ghost** [comment]
I re-installed the repo and I entered http://localhost:5000 for Site URL, Mobile URL and Valid OAuth redirect URIs on the FB app config. Now it's working.
